### ISSUE TITLE
Purist Services Parent Ticket

### ISSUE THREAD

**Issue by toddatpurism** [purism/purist#1]
- [x] #2 Encrypted Authentication Service
- [ ] #3 Encrypted Purist Service DNS Lookup 
- [ ] #4 Encrypted Account Creation
- [ ] #5 Encrypted Email
- [ ] #6 Encrypted Cloud Storage
- [ ] #7 Encrypted Instant Messaging
- [ ] #8 Encrypted Voice Calling
- [ ] #9 Encrypted Video Calling
- [ ] #10 Encrypted Public Messaging
- [ ] #11 Encrypted Contact List
- [ ] #12 Encrypted Key Storage/Exchange
- [ ] #13 Encrypted Calendaring
- [ ] ... others to come ...
